/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.21
 * Generated at: 2014-03-26 23:00:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class logout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>Logout</title>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("            \n");
      out.write("html {\n");
      out.write("    overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("html, body {\n");
      out.write("\tmargin:0;\n");
      out.write("\tpadding:0;\n");
      out.write("\tborder:0;\n");
      out.write("\toutline:0;\n");
      out.write("\tfont-weight:inherit;\n");
      out.write("\tfont-style:inherit;\n");
      out.write("\tfont-size:100%;\n");
      out.write("\tfont-family:inherit;\n");
      out.write("\tvertical-align:baseline;\n");
      out.write("        height: 100%;\n");
      out.write("        width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(":focus {\n");
      out.write("\toutline:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul {\n");
      out.write("\tlist-style:none;\n");
      out.write("\tfont-size:1.1em;\n");
      out.write("\tpadding:0 0 18px 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* browser default font-size is 16px which is too big so we make it 16px x 62.5% = 10px */\n");
      out.write("body {\n");
      out.write("\tfont:normal 400 62.5%/1.0 Arial,Verdana,Helvetica,sans-serif;\n");
      out.write("\tmin-width:960px;\n");
      out.write("\tbackground:#000;\n");
      out.write("\tcolor:#333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* CONTENT --------------------------------- */\n");
      out.write("#content {\n");
      out.write("\tpadding:0;\n");
      out.write("\tmargin:0;\n");
      out.write("        position: fixed;\n");
      out.write("        left: 50%;\n");
      out.write("        top: 50%;\n");
      out.write("        height: 250px;\n");
      out.write("        width: 450px;\n");
      out.write("        overflow: auto;\n");
      out.write("        margin-top: -125px;\n");
      out.write("        margin-left: -225px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* MESSAGES --------------------------------- */\n");
      out.write(".info, .success {\n");
      out.write("\tclear:both;\n");
      out.write("\tmargin:18px 0;\n");
      out.write("\tpadding:20px 20px 20px 100px;\n");
      out.write("\tfont-size:10px;\n");
      out.write("        background-color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".success {\n");
      out.write("\tborder:2px solid #000;\n");
      out.write("\t/*background:#dfa url(../images/confirm.gif) no-repeat 20px 18px;*/\n");
      out.write("\tcolor:#000000;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content .errors h2, #content .success h2 {\n");
      out.write("\tfont-family:Arial,Verdana,Helvetica,sans-serif;\n");
      out.write("\tfont-size:18px;\n");
      out.write("\tline-height:48px;\n");
      out.write("\tfont-weight:400;\n");
      out.write("\tmargin:0 18px 0 0;\n");
      out.write("\tpadding:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content .success h2 {\n");
      out.write("\tcolor:#000 !important;\n");
      out.write("        font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* begin new styles  -----------------------------------------------------------------------------------------------*/\n");
      out.write("\n");
      out.write("#background.mozilla {\n");
      out.write("        background-image: url('themes/a_default.theme/images/stripes_rpt.png'),-moz-radial-gradient(white, #e6e7e8);\n");
      out.write("        background-position: center center,center center;\n");
      out.write("        background-repeat: repeat,no-repeat,no-repeat;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#background.chrome {\n");
      out.write("        background-image: url('themes/a_default.theme/images/stripes_rpt.png'),-webkit-radial-gradient(white, #e6e7e8);\n");
      out.write("        background-position: center center,center center;\n");
      out.write("        background-repeat: repeat,no-repeat,no-repeat;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#background.ie {\n");
      out.write("        background-color: #f6f6f7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#background.ie #mainpanel {\n");
      out.write("        background: url('themes/a_default.theme/images/stripes_rpt.png') repeat center center;\n");
      out.write("        height: 100%;\n");
      out.write("        width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t</style>\n");
      out.write("</head>\n");
      out.write("\n");

        String ua = request.getHeader( "User-Agent" );
        boolean isFirefox = ( ua != null && ua.indexOf( "Firefox/" ) != -1 );
        boolean isIE = ( ua != null && ua.indexOf( "MSIE" ) != -1 );
        response.setHeader( "Vary", "User-Agent" );
    
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if( isFirefox ){ 
      out.write("\n");
      out.write("    <body id=\"background\" class=\"mozilla\">\n");
      out.write("    ");
 } else if( isIE ){ 
      out.write("\n");
      out.write("    <body id=\"background\" class=\"ie\">\n");
      out.write("        <div id=\"mainpanel\">\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <body id=\"background\" class=\"chrome\">\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    \n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"hdr\">\n");
      out.write("            <div class=\"left\">\n");
      out.write("              <div class=\"logoLeft\"></div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    ");
 if( isIE ){ 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    \n");
      out.write("\t\t<div id=\"content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div id=\"msg\" class=\"success\">\n");
      out.write("\t\t\t<h2>Logout successful</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>You have successfully logged out. Please enter your User ID and Password to login again.</p>\n");
      out.write("\t\t\t<p>For security reasons, exit your web browser.</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("    ");
 if( isIE ){ 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\t</body>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
